spring:
    application:
        name: barber-shop-api
    datasource:
        url: jdbc:postgresql://localhost:5432/barberApi
        username: postgres
        password: 123a123a
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    devtools:
        remote:
            secret: 123
        restart:
            trigger-file: trigger.txt
